### ISSUE TITLE
Missing info on git repository accounts in Readme.md

### ISSUE THREAD

**Issue by typo3gov** [t3kit/t3kit_vagrant#3]
Hi,
I installed the vagrant package and noticed that existing user accounts at GitHub and Bitbucket with added SSH keys are required to run the installation without errors. This might be obvious for experienced developers but also might annoy not so experienced users. I tried to create a branch/Pull request for the Readme.md but it seems I`m not allowed to do so. So I just send you my addition to the Readme.md here:

#### Additional requirements
- Existing GitHub user account with added [SSH key](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)
- Existing Bitbucket user account with added [SSH key](https://confluence.atlassian.com/bitbucket/add-an-ssh-key-to-an-account-302811853.html)

all the best,
Sacha

**Comment by dmh** [comment]
Thanks for interest and help.
